import { StyleSheet,Platform,Dimensions } from "react-native";
import themeProvider from "./theme";
const stylesCon = () => {
   const colors =  themeProvider().colors ;
   const stylesS = StyleSheet.create({
     home: {
       flex: 1,
       backgroundColor: colors.bg_1,
     },
     loaderContainer: {
       position: "absolute",
       width: "100%",
       height: "100%",
       backgroundColor: colors.app_4,
       justifyContent: "center",
     },
     loader: {
       backgroundColor: colors.bg_3,
       flex: 1,
     },
     ///Home
     homeBoardCon: {
       justifyContent: "center",
       alignItems: "center",
       left: 0,
       right: 0,
       padding: 10,
     },
     userBoard: {
       flex: 1,
       marginTop: 30,
       backgroundColor: colors.app_1,
       height: 210,
       width: "90%",
       borderRadius: 25,
       // justifyContent: "center",
       // alignItems: "center",
       flexDirection: "row",
       shadowColor: colors.app_1,
       shadowOpacity: 0.2,
       shadowRadius: 10,
       shadowOffset: { x: 10, y: 10 },
     },
     dataLeftCon: {
       flex: 1,
       alignItems: "center",
       justifyContent: "flex-start",
     },
     txtLive: {
       fontSize: 21,
       fontWeight: "900",
       color: colors.bg_3,
       fontFamily: "Roboto_Bold",
     },

     liveNo: {
       fontSize: 75,
       fontWeight: "900",
       color: "#333",
       fontFamily: "Roboto_Bold",
       marginBottom: 5,
     },
     liveDate: {
       fontSize: 13,
       color: colors.text_1b,
       fontFamily: "Roboto",
     },
     dataMidCon: {
       flex: 2,
       alignItems: "center",
       justifyContent: "center",
     },

     dataRightCon: {
       flex: 1,
       width: 75,
       alignItems: "flex-end",
       justifyContent: "flex-start",
     },
     langBtn: {
       width: 75,
       padding: 10,
       marginTop: 35,
       flexDirection: "row",
       justifyContent: "center",
       alignItems: "center",
       backgroundColor: colors.bg_3,
       borderTopLeftRadius: "25%",
       borderBottomLeftRadius: "25%",
     },
     langLot: {
       position: "absolute",
       right: -10,
       width: 35,
       height: 35,
     },
     homeDataCon: {
       justifyContent: "center",
       alignItems: "center",
       backgroundColor: "transparent",
     },
     //TwoDmini
     twoDmini: {
       flex: 1,
       width: "90%",
     },
     dataA: {
       marginVertical: 10,
       flex: 1,
       padding: 5,
       backgroundColor: colors.bg_3,
       borderRadius: 10,
       alignItems: "center",
       shadowColor: colors.text_1,
       shadowOpacity: 0.1,
       shadowRadius: 7,
       shadowOffset: { x: 10, y: 10 },
     },
     dataHeader: {
       color: colors.text_1,
       fontSize: 21,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
       marginVertical: 5,
     },
     dataACon: {
       borderTopColor: colors.text_3,
       borderTopWidth: 1,
       flexDirection: "row",
       justifyContent: "space-between",
     },
     dataCon: {
       flex: 1,
       justifyContent: "center",
       alignItems: "center",
       paddingVertical: 10,
     },
     dataH: {
       fontSize: 15,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
       color: colors.text_2,
     },
     dataV: {
       fontSize: 18,
       fontFamily: "Roboto_Bold",
       color: colors.text_1,
       fontWeight: "700",
     },
     line: {
       width: "90%",
       height: 2,
       flex: 1,
       backgroundColor: colors.text_4,
       marginVertical: 5,
     },
     //Service Internet and Modern Data
     internetDataCon: {
       flex: 1,
       width: "90%",
       borderRadius: 10,
       backgroundColor: colors.bg_2,
       overflow: "hidden",
     },
     interData: {
       flexDirection: "row",
       height: 100,
       alignItems: "center",
       justifyContent: "space-between",
       borderRadius: 10,
       shadowColor: colors.app_1,
       shadowOffset: { x: 10, y: 10 },
       shadowRadius: 10,
       shadowOpacity: 0.3,
     },
     interLeft: {
       flex: 1,
       alignItems: "center",
       justifyContent: "space-between",
       gap: 20,
     },
     interRight: {
       flex: 1,
       alignItems: "center",
       justifyContent: "space-between",
       gap: 20,
     },
     inter: {
       padding: 5,
       alignItems: "center",
     },
     interHeader: {
       color: colors.app_2,
       fontSize: 16,
       fontWeight: "500",
       fontFamily: "Roboto_Bold",
     },
     interH: {
       color: colors.app_3,
       fontSize: 21,
       fontFamily: "Roboto_Bold",
     },
     interV: {
       color: colors.text_1,
       fontSize: 17,
       fontFamily: "Roboto_Bold",
       fontWeight: "700",
     },
     interData3D: {
       flexDirection: "row",
       backgroundColor: colors.bg_2,
       padding: 10,
       marginVertical: 10,
       alignItems: "center",
       justifyContent: "space-around",
       borderRadius: 5,
       shadowColor: colors.bg_1,
       shadowOffset: { x: 5, y: 5 },
       shadowRadius: 10,
       shadowOpacity: 0.3,
       width: "90%",
     },
     threeDTxt: {
       textAlign: "center",
       fontFamily: "Roboto_Bold",
       fontSize: 16,
       color: colors.app_4,
       fontWeight: "600",
     },
     homeBottom: {
       flexDirection: "row",
       alignItems: "center",
       justifyContent: "space-around",
       marginVertical: 5,
     },
     homeBtns: {
       padding: 10,
       borderRadius: 20,
       width: "45%",
       margin: 5,
       alignItems: "center",
       justifyContent: "center",
       backgroundColor: colors.app_4,
     },
     //Image
     imageSliderCon: {
       height: 200,
       borderRadius: 10,
       width: "98%",
       backgroundColor: colors.bg_1,
       alignSelf: "center",
       overflow: "hidden",
       marginVertical: 10,
     },

     //buttons
     btnBlurCon: {
       width: "100%",
       height: "100%",
       position: "absolute",
       bottom: 0,
       left: 0,
     },
     btnContainer: {
       flex: 1,
       justifyContent: "center",
       alignItems: "center",
       padding: 10,
       position: "relative",
     },
     btnLabelTxt: {
       color: colors.app_2,
       fontSize: 16,
     },

     regBtn: {
       width: "80%",
       padding: 15,
       borderRadius: 10,
       backgroundColor: colors.bg_1,
       alignItems: "center",
       justifyContent: "center",
       marginVertical: 20,
     },
     regBtnTxt: {
       fontSize: 18,
       color: colors.app_4,
       fontWeight: "600",
     },
     logBtn: {
       alignItems: "center",
       justifyContent: "center",
       padding: 15,
       width: "80%",
       borderRadius: 10,
       backgroundColor: colors.app_1,
     },
     logBtnTxt: {
       fontSize: 18,
       fontWeight: "600",
       color: colors.text_1b,
     },
     twoD: {
       flex: 1,
       backgroundColor: colors.bg_1,
     },
     threeD: {
       flex: 1,
       backgroundColor: colors.bg_1,
     },
     //Wallet///////////////////////////////////
     linearCon: {
       flex: 1,
       justifyContent: "space-between",
     },
     wallets: {
       height: "100%",
       backgroundColor: colors.bg_2,
       padding: 0,
     },
     WALLETscrollView: {
       flex: 1,
       padding: 0,
       backgroundColor: colors.bg_2,
     },
     walletTopCon: {
       flexDirection: "row",
       justifyContent: "space-between",
       alignItems: "center",
       paddingHorizontal: 20,
      //  paddingTop: 25,
       flex: 0.5,
       backgroundColor: colors.bg_2,
     },
     walletTopL: {
       padding: 5,
       borderRadius: "10%",
       backgroundColor: colors.bg_1,
     },

     walletTopR: {
       padding: 3,
       borderRadius: "100%",
       backgroundColor: colors.app_1,
     },
     walletImage: {
       width: 55,
       height: 55,
     },
     wallet: {
       flex: 6,
       backgroundColor: colors.bg_2,
     },
     walletMainCon: {
       flex: 1.5,
       flexDirection: "row",
     },
     walletMain: {
       flex: 1,
       justifyContent: "space-around",
       alignItems: "center",
     },
     scanBtn: {
       alignItems: "center",
       justifyContent: "center",
       backgroundColor: colors.bg_1,
       borderRadius: "15%",
       width: "80%",
       height: 90,
     },
     walletBtnTxt: {
       color: colors.text_1b,
       fontWeight: "500",
       fontSize: 16,
     },
     ballanceCon: {
       flex: 2,
       backgroundColor: colors.app_1,
       margin: 10,
       borderRadius: 10,
       overflow: "hidden",
     },
     ballanceHeader: {
       color: colors.text_1b,
       fontSize: 13,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",

       marginLeft: 20,
     },
     ballanceD: {
       marginLeft: 20,
       margin: 5,
       color: colors.text_1b,
       fontSize: 32,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
     },
     ballanceBox: {
       flexDirection: "row",
       marginVertical: 10,
       justifyContent:"space-between",
       
     
     },
     balanceCon: {
       padding: 10,
     },

     balanceNo: {
       color: colors.text_1b,
       fontSize: 19,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
       marginLeft: 20,
     },
     userTxt: {
       color: colors.bg_2,
       fontSize: 17,
       fontFamily: "Roboto_Bold",
       fontWeight: "400",
       marginLeft: 10,
     },
     qrCodePressed: {
       backgroundColor: colors.bg_1,
       padding: 10,
       borderRadius: "10%",
       height: "100%",
       width: "100%",
       justifyContent: "center",
       alignItems: "center",
     },
     qrCodeBtn: {
       backgroundColor: colors.bg_1,
       borderRadius: "20%",
       margin: 5,
       position: "absolute",
       width: 70,
       height: 70,
       right: 10,
       bottom: 10,
       justifyContent: "center",
       alignItems: "center",
     },
     eye: {
       justifyContent: "center",
       alignItems: "center",
       paddingVertical: 5,
       marginRight:25
     },
     ///wallet bottom part
     walletBottomCon: {
       flex: 3,
       alignItems: "center",
     },
     walletBtnCon: {
       flexDirection: "row",
       alignItems: "center",
       justifyContent: "space-around",
       padding: 15,
     },
     walletBtnCons: {
       alignItems: "center",
       flex: 1,
     },
     walletBtns: {
       backgroundColor: colors.bg_3,
       width: 85,
       marginBottom: 5,
       alignItems: "center",
       borderRadius: "16%",
     },
     walletBtnImg: {
       width: 60,
       height: 60,
     },
     scanLoti: {
       width: 70,
       height: 70,
     },
     walletBtnTxt: {
       color: colors.app_1,
       fontSize: 13,
       fontFamily: "Roboto_Bold",
       fontWeight: "500",
     },
     walletBtnsTxt: {
       color: colors.text_1,
       fontSize: 14,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
     },
     walletSliderCon: {
       marginTop: 10,
       height: 150,
       width: "100%",
     },
     carouselCon: {
       flex: 1,
     },

     paymentsCon: {
       height: 500,
       width: "95%",
     },
     paymentHeader: {
       color: colors.text_3,
       fontSize: 16,
       fontFamily: "Roboto_Bold",
       fontWeight: "700",
       marginBottom: 5,
       textAlign: "center",
      
     },
     payments: {
       width: "100%",
       padding: 5,
       flexDirection: "row",
       backgroundColor: colors.bg_3,
       alignItems: "center",
       borderRadius: 5,
       marginVertical: 5,
     },
     gotoPayBtn: {
       padding: 10,
       borderRadius: "25%",
       backgroundColor: colors.app_1,
       margin: 35,
       alignItems: "center",
       justifyContent: "center",
     },
     Payments: {
       width: 120,
       height: 185,
       backgroundColor: colors.bg_3,
       alignItems: "center",
       marginHorizontal: 5,
       borderRadius: 15,
       justifyContent: "space-between",
       position:"relative"
     },
     Payment: {
       alignItems: "center",
       padding: 10,
       // justifyContent:"space-between"
     },
     PaymentImg: {
       width: "100%",
       height: 110,
       borderTopLeftRadius: 15,
       borderTopRightRadius: 10,
     },
     paymentImg: {
       width: 50,
       height: 50,
       borderRadius: 5,
     },
     payment: {
       marginHorizontal: 5,
       flex: 1,
     },
     paymentN: {
       color: colors.text_2,
       fontSize: 14,
       fontFamily: "Roboto_Bold",
       fontWeight: "700",
       margin: 5,
     },
     paymentP: {
       color: colors.text_3,
       fontSize: 14,
       fontFamily: "Roboto_Bold",
       fontWeight: "500",
       
     },
     paymentEd: {
       padding:10,
       backgroundColor: colors.bg_3b,
       borderBottomLeftRadius:30,
      //  borderTopRightRadius:15,
       position:"absolute",
       top:-5,
       right:0,
       zIndex:1

     },
    //  paymentEdTxt: {
    //    color: colors.text_1b,
    //    fontSize: 14,
    //    fontFamily: "Roboto_Bold",
    //    fontWeight: "500",
    //  },

     ///Screens
     Container: {
       flex: 1,
       backgroundColor: colors.bg_2,
     },
     topCon: {
       backgroundColor: colors.app_1,
       flex: 1,
     },
     bottomCon: {
       flex: 3,
     },
     //Login Screen
     loginCon: {
       flex: 1,
       backgroundColor: colors.bg_2,
       justifyContent: "center",
       alignItems: "center",
       paddingTop: 20,
     },
     loginBoxCon: {
       flex: 3,
       width: "90%",
       backgroundColor: "transparent",
       borderCurve: "continuous",
       borderRadius: 20,
       justifyContent: "center",
       alignItems: "center",
     },
     loginHeader: {
       fontSize: 26,
       fontFamily: "Roboto_Bold",
       fontWeight: "900",
       marginVertical: 20,
       color: colors.app_1,
       shadowColor: colors.bg_1,
       shadowOpacity: 0.4,
       shadowRadius: 10,
       shadowOffset: { x: 10, y: 10 },
     },
     inputName: {
       paddingVertical: 10,
       backgroundColor: colors.bg_3,
       paddingLeft: 60,
       width: "90%",
       borderRadius: 10,
       fontSize: 19,
       fontFamily: "Roboto",
       color: colors.app_1,
       shadowColor: colors.bg_1,
       shadowOpacity: 0.5,
       shadowRadius: 10,
       shadowOffset: { x: 10, y: 20 },
       borderWidth: 2,
     },
     inputPwd: {
       paddingVertical: 10,
       backgroundColor: colors.bg_3,
       paddingLeft: 60,
       width: "90%",
       borderRadius: 10,
       fontSize: 19,
       fontFamily: "Roboto",
       color: colors.app_1,
       marginBottom: 50,
       shadowColor: colors.bg_1,
       shadowOpacity: 0.5,
       shadowRadius: 10,
       shadowOffset: { x: 10, y: 20 },
       borderWidth: 2,
     },
     loginSubBtn: {
       width: "90%",
       padding: 10,
       backgroundColor: colors.app_1,
       justifyContent: "center",
       alignItems: "center",
       borderRadius: "25%",
       shadowColor: colors.bg_1,
       shadowOpacity: 0.5,
       shadowRadius: 10,
       shadowOffset: { x: 10, y: 20 },
     },
     loginBtnTxt: {
       fontSize: 19,
       color: colors.text_1b,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
     },
     loginLine: {
       backgroundColor: colors.app_2,
       height: 2,
       width: "80%",
       marginTop: 25,
       marginBottom: 5,
     },
     loginRegTxt: {
       fontSize: 14,
       fontFamily: "Roboto",
       fontStyle: "italic",
       color: colors.bg_2,
     },
     //RegBtn in Login
     RegBtnCon: {
       width: "90%",
       padding: 10,
       backgroundColor: colors.bg_3b,
       justifyContent: "center",
       alignItems: "center",
       borderRadius: "25%",
       margin: 10,
       shadowColor: colors.bg_3,
       shadowOpacity: 0.5,
       shadowRadius: 10,
       shadowOffset: { x: 10, y: 20 },
     },
     RegBtnTxt: {
       color: colors.app_1,
       fontSize: 19,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
     },
     //img
     loginImgCon: {
       flex: 1,
       justifyContent: "center",
       alignItems: "center",
     },
     loginImg: {
       height: 220,
       width: 200,
     },
     //Register Screen Container
     RegScreenCon: {
       flex: 1,
       backgroundColor: colors.bg_2,
       alignItems: "center",
       justifyContent: "center",
     },
     RegBoxCon: {
       flex: 1,
       width: "90%",
       alignItems: "center",
       justifyContent: "center",
       backgroundColor: colors.bg_2,
     },
     regNo: {
       backgroundColor: colors.bg_3,
       borderRadius: 10,
       width: "90%",
       padding: 10,
       color: colors.app_1,
       borderColor: colors.app_1,
       borderWidth: 2,
       paddingLeft: 50,
       fontSize: 19,
       shadowColor: colors.bg_1,
       shadowOpacity: 0.5,
       shadowRadius: 10,
       shadowOffset: { x: 10, y: 20 },
     },
     reg2FaBox: {
       width: "90%",
       flexDirection: "row",
       justifyContent: "space-between",
       alignItems: "center",
     },
     regInput2Fa: {
       width: "50%",
       padding: 10,
       backgroundColor: colors.bg_3,
       color: colors.app_1,
       fontSize: 19,
       borderColor: colors.app_1,
       borderWidth: 2,
       paddingLeft: 50,
       borderRadius: 10,
       shadowColor: colors.bg_1,
       shadowOpacity: 0.5,
       shadowRadius: 10,
       shadowOffset: { x: 10, y: 10 },
     },
     reg2FaBtn: {
       width: "40%",
       padding: 10,
       backgroundColor: colors.bg_3,
       alignItems: "center",
       justifyContent: "center",
       borderRadius: "10%",
       shadowColor: colors.bg_1,
       shadowOpacity: 0.5,
       shadowRadius: 10,
       shadowOffset: { x: 10, y: 20 },
     },
     reg2FaBtnTxt: {
       fontSize: 19,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
       color: colors.app_1,
     },
     regPwd: {
       width: "90%",
       padding: 10,
       backgroundColor: colors.bg_3,
       color: colors.app_1,
       fontSize: 19,
       borderColor: colors.app_1,
       borderWidth: 2,
       paddingLeft: 50,
       borderRadius: 10,
       shadowColor: colors.bg_1,
       shadowOpacity: 0.5,
       shadowRadius: 10,
       shadowOffset: { x: 10, y: 10 },
     },
     regPwdTxt: {
       color: colors.app_1,
       fontSize: 10,
       fontFamily: "Roboto",
     },
     subValTxt: {
       color: colors.app_1,
       fontSize: 14,
       fontFamily: "Roboto",
       marginTop: 10,
     },
     regSubBtn: {
       marginTop: 20,
       backgroundColor: colors.app_1,
       padding: 13,
       width: "90%",
       justifyContent: "center",
       alignItems: "center",
       borderRadius: "25%",
       shadowColor: colors.bg_1,
       shadowOpacity: 0.5,
       shadowRadius: 10,
       shadowOffset: { x: 10, y: 20 },
     },
     rebSubTxt: {
       fontSize: 19,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
       color: colors.text_1b,
     },
     loginBtn: {
       backgroundColor: colors.bg_3b,
       margin: 10,
       padding: 10,
       width: "90%",
       justifyContent: "center",
       alignItems: "center",
       borderRadius: "25%",
       shadowColor: colors.bg_2,
       shadowOpacity: 0.5,
       shadowRadius: 10,
       shadowOffset: { x: 10, y: 10 },
     },
     logRegTxt: {
       fontSize: 19,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
       color: colors.app_4,
     },
     RegLogTxt: {
       fontSize: 14,
       fontStyle: "italic",
       fontFamily: "Roboto",
       color: colors.app_1,
     },
     //label
     inputLabel: {
       margin: 10,
       fontSize: 15,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
       paddingLeft: 20,
       alignSelf: "flex-start",
       color: colors.app_1,
     },
     //Service Container
     servicesCon: {
       flexDirection: "row",
       width: "90%",
       padding: 10,
       alignItems: "center",
       justifyContent: "space-around",
     },
     serviceImg: {
       width: 100,
       height: 100,
     },
     serviceUs: {
       width: 120,
       height: 120,
     },
     termofus: {
       position: "absolute",
       bottom: -10,
       fontSize: 13,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
       color: colors.app_1,
       textAlign: "center",
       left: "10%",
       right: "10%",
     },
     /// Service BTN
     serviceBtnCon: {
       position: "absolute",
       right: 20,
       bottom: 40,
       borderRadius: "50%",
       padding: 10,
       zIndex: 9,
       backgroundColor: colors.app_1,
     },
     ///More
     topmeCon: {
       flex: 1,
       backgroundColor: colors.app_1,
       padding: 10,
       borderBlockColor: colors.bg_1,
       borderBottomWidth: 3,
       borderBottomLeftRadius: -30,
     },
     userProfileCon: {
       width: "90%",
       height: "100%",
       // paddingTop: 20,
       flexDirection: "row",
       alignItems: "center",
     },
     userProfile: {
       width: 75,
       height: 75,
       borderColor: colors.app_1,
       borderWidth: 3,
       borderRadius: 50,
       margin: 10,
     },

     userDataBox: {
       margin: 10,
       flex: 1,
     },
     userNameTxt: {
       fontSize: 21,
       fontFamily: "Roboto_Bold",
       fontWeight: "900",
       width: "100%",
       color: colors.app_4,
       margin: 5,
     },
     userDataTxt: {
       fontSize: 17,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
       padding: 5,
       color: colors.bg_3c,
     },
     bottomMeCon: {
       flex: 5,
     },
     moreItemCon: {
       flexDirection: "row",
       backgroundColor: colors.bg_3,
       shadowColor: colors.bg_1,
       shadowOpacity: 0.4,
       shadowRadius: 10,
       shadowOffset: { x: 10, y: 10 },
       marginHorizontal: 20,
       marginVertical: 10,
       alignItems: "center",
       borderRadius: 10,
       padding: 5,
       height: 75,
     },
     moreItemImg: {
       width: 60,
       height: 60,
       marginRight: 10,
     },
     moreItemTxt: {
       fontSize: 17,
       fontFamily: "Roboto_Bold",
       fontWeight: "800",
       margin: 5,
       color: colors.text_2,
     },

     //Me Screen
     meTop: {
       flex: 1,
       backgroundColor: colors.bg_2,
     },
     meProfile: {
       flex: 1,
       height: "100%",
       width: "100%",
       backgroundColor: colors.bg_2,
       alignSelf: "center",
       zIndex: 1,
       overflow: "hidden",
       alignItems: "center",
       justifyContent: "center",
     },
     meImg: {
       width: 210,
       height: 210,
       borderRadius: 210,
       borderWidth: 4,
       borderColor: colors.app_1,
     },
     meBottom: {
       flex: 2,
       backgroundColor: colors.bg_2,
     },
     changePhBtnCon: {
       paddingVertical: 10,
       flexDirection: "row",
       justifyContent: "space-around",
       alignItems: "center",
       paddingHorizontal: 20,
     },
     ///Change Profile Btn
     changeProfileBtn: {
       backgroundColor: colors.bg_3,
       borderRadius: 30,
       justifyContent: "center",
       alignItems: "center",
       padding: 15,
       paddingHorizontal: 30,
       borderColor: colors.app_1,
       borderWidth: 2,
     },

     meNameChangeCon: {
       flex: 1,
       alignItems: "center",
       justifyContent: "space-around",
     },
     infoChangeCon: {
       width: "100%",
       flex: 1,
       alignItems: "center",
     },
     upgradeBtn: {
       padding: 20,
       backgroundColor: colors.bg_3b,
       borderRadius: 10,
       marginVertical: 20,
     },
     nameChangeInputCon: {
       alignItems: "center",
       flexDirection: "row",
       color: colors.text_1,
       fontSize: 21,
       fontFamily: "Roboto_Bold",
       fontWeight: "700",
     },
     editBtn: {
       zIndex: 0,
       width: 34,
       height: 34,
     },
     nameChangeInput: {
       padding: 17,
       backgroundColor: colors.bg_3,
       width: "85%",
       borderRadius: 10,
       marginVertical: 5,
       borderLeftColor: colors.app_1,
       borderLeftWidth: 5,
       borderRightWidth: 5,
       borderRightColor: colors.app_1,
       shadowColor: colors.bg_1,
       shadowOpacity: 0.9,
       shadowOffset: { x: 10, y: 20 },
       shadowRadius: 10,
       zIndex: 1,
       flexDirection: "row",
       justifyContent: "space-between",
     },
     meTxt: {
       fontFamily: "Roboto_Bold",
       fontSize: 19,
       fontWeight: "600",
       color: colors.text_3,
     },
     nameChangeBtn: {
       backgroundColor: colors.app_4,
       padding: 15,
       width: "80%",
       borderRadius: "25%",
       alignItems: "center",
       justifyContent: "center",
       shadowColor: colors.bg_1,
       shadowOpacity: 0.9,
       shadowOffset: { x: 10, y: 20 },
       shadowRadius: 10,
       marginVertical: 25,
     },
     saveTxt: {
       fontFamily: "Roboto_Bold",
       fontSize: 19,
       fontWeight: "600",
       color: colors.text_1b,
     },
     red: {
       fontFamily: "Roboto_Bold",
       fontSize: 14,
       fontWeight: "600",
       color: "red",
       margin: 10,
     },
     ///Pwd Change Screen
     PwdContainer: {
       flex: 1,
       paddingTop: 20,
       alignItems: "center",
       justifyContent: "space-between",
       backgroundColor: colors.bg_2,
     },
     pwdInputConM: {
       alignItems: "center",
     },
     pwdInputCon: {
       flexDirection: "row",
       alignItems: "center",
       width: "90%",
       marginVertical: 10,
       alignSelf: "center",
     },
     pwdChangeInput: {
       width: "100%",
       paddingVertical: 20,
       paddingHorizontal: 20,
       backgroundColor: colors.bg_3,
       borderRadius: 10,
       color: colors.text_1,
       fontSize: 18,
       borderLeftColor: colors.app_1,
       borderLeftWidth: 5,
       borderRightWidth: 5,
       borderRightColor: colors.app_1,
     },
     pwdChangeBtn: {
       backgroundColor: colors.app_1,
       borderRadius: 10,
       padding: 20,
       width: "90%",
       marginVertical: 5,
       justifyContent: "center",
       alignItems: "center",
       minWidth: "90%",
     },
     Eye1: {
       position: "absolute",
       right: 20,
     },
     pwdChangetxt: {
       fontFamily: "Roboto_Bold",
       fontSize: 18,
       fontWeight: "600",
       color: colors.bg_1,
     },

     ///3D UIX
     threeDCon: {
       flex: 1,
       backgroundColor: colors.bg_2,
     },
     threeDTopCon: {
       flex: 0.7,
       backgroundColor: colors.app_1,
     },
     threeDdataCon: {
       backgroundColor: colors.bg_2,
       flex: 6,
     },
     _3d_betBtn: {
       position: "absolute",
       bottom: 20,
       left: "25%",
       right: "25%",
       borderRadius: "25%",
       backgroundColor: colors.app_4,
       justifyContent: "center",
       alignItems: "center",
       paddingVertical: 10,
       shadowColor: colors.bg_1,
       shadowOpacity: 0.9,
       shadowOffset: { x: 10, y: 20 },
       shadowRadius: 10,
     },
     _3d_betBtnTxt: {
       fontFamily: "Roboto_Bold",
       fontSize: 21,
       fontWeight: "600",
       color: colors.text_1b,
     },
     threeDItem: {
       backgroundColor: colors.bg_3,
       height: 90,
       width: "80%",
       margin: 10,
       alignSelf: "center",
       borderRadius: 10,
       shadowColor: colors.bg_1,
       shadowOffset: { x: 10, y: 20 },
       shadowOpacity: 0.5,
       shadowRadius: 10,
       flexDirection: "row",
       justifyContent: "space-around",
       alignItems: "center",
     },
     threeDheaderCon: {
       alignItems: "center",
       justifyContent: "center",
     },
     threeDvalueCon: {
       alignItems: "center",
     },
     //TOP
     //  threeDTopCon: {
     //    height: 170,
     //  },
     //ServerTime
     serverTimeCon: {
       paddingTop: 35,
       flexDirection: "row",
       backgroundColor: colors.app_1,
       alignItems: "center",
     },
     serverTime: {
       color: colors.text_1b,
       padding: 10,
       fontSize: 18,
       fontFamily: "Roboto_Bold",
       fontWeight: "700",
     },
     threeDBtnBox: {
       flex: 1,
       flexDirection: "row",
       justifyContent: "space-around",
       alignItems: "center",
     },
     ////History BTNs
     btnTxt: {
       fontFamily: "Roboto_Bold",
       fontSize: 18,
       fontWeight: "600",
       color: colors.text_1b,
     },
     //  HistoryBtn: {
     //    padding: 10,
     //    paddingHorizontal: 25,
     //    backgroundColor: colors.app_4,
     //    borderRadius: "25%",
     //  },
     //  WinnerBtn: {
     //    padding: 10,
     //    paddingHorizontal: 25,
     //    backgroundColor: colors.app_4,
     //    borderRadius: "25%",
     //  },
     //  AnalysisBtn: {
     //    paddingHorizontal: 25,
     //    padding: 10,
     //    backgroundColor: colors.app_4,
     //    borderRadius: "25%",
     //  },

     //2D Screen
     top2DCon: {
       flex: 2,
       backgroundColor: colors.bg_2,
     },
     _2dTopCon: {
       paddingTop: 30,
       height: 110,
       flexDirection: "row",
       backgroundColor: colors.app_1,
       width: "100%",
       alignItems: "center",
       justifyContent: "space-around",
     },
     _2dTopAbCon: {
       height: 120,
       position: "absolute",
       left: 0,
       flexDirection: "row",
       right: 0,
       top: "50%",
       padding: 10,
       gap: 10,
     },
     bg: {
       height: "100%",
       flex: 1,
       opacity: 1,

       alignItems: "center",
       justifyContent: "space-between",
     },
     morningCon: {
       flex: 1,
       borderRadius: 10,
       overflow: "hidden",
       backgroundColor: colors.text_1b,
     },

     //  _2dBtn: {
     //    backgroundColor: colors.bg_2,
     //    paddingHorizontal: 30,
     //    borderRadius: "25%",
     //    padding: 10,
     //    shadowColor: colors.bg_2,
     //    shadowOffset: { x: 10, y: 20 },
     //    shadowOpacity: 0.5,
     //    shadowRadius: 10,
     //  },
     _2dBtnTxt: {
       fontFamily: "Roboto_Bold",
       fontSize: 19,
       fontWeight: "600",
       color: colors.bg_2,
     },
     _2d_liveCon: {
       flex: 1,
       justifyContent: "center",
       alignItems: "center",
     },
     _2d_liveNo: {
       fontSize: 70,
       fontFamily: "Roboto_Bold",
       fontWeight: "900",
       color: colors.bg_1,
     },
     //  _2d_live: {
     //    fontSize: 12,
     //    fontFamily: "Roboto_Bold",
     //    fontWeight: "600",
     //    color: colors.app_2,
     //  },
     //bottom
     bottom2DCon: {
       flex: 4.5,
       backgroundColor: colors.bg_2,
     },
     _2d_dataCon: {
       flex: 1,
     },
     _2d_itemCon: {
       backgroundColor: colors.bg_3,
       margin: 20,
       height: 420,
       borderRadius: 10,
       shadowColor: colors.bg_1,
       shadowOffset: { x: 10, y: 20 },
       shadowOpacity: 0.7,
       shadowRadius: 10,
     },
     _2d_itemTop: {
       backgroundColor: colors.app_1,
       flex: 1,
       borderTopLeftRadius: 20,
       borderTopRightRadius: 20,
       justifyContent: "center",
       alignItems: "center",
     },
     _2d_Header: {
       fontFamily: "Roboto_Bold",
       fontSize: 19,
       fontWeight: "600",
       color: colors.text_1b,
     },
     _2d_itemBottom: {
       flex: 6,
       backgroundColor: colors.bg_3,
       borderRadius: 5,
       alignItems: "center",
       paddingTop: 10,
     },
     _2d_H: {
       margin: 10,
       fontSize: 21,
       color: colors.text_1,
       fontFamily: "Roboto_Bold",
       fontWeight: "700",
     },
     _2d_line: {
       height: 2,
       width: "90%",
       backgroundColor: colors.bg_3b,
     },
     _2d_bt_af: {
       width: "100%",

       flexDirection: "row",
       alignItems: "center",
       justifyContent: "space-around",
       padding: 10,
       borderBottomColor: colors.bg_2,
       borderBottomWidth: 5,
     },
     _2d_bt_ev: {
       flexDirection: "row",
       alignItems: "center",
       justifyContent: "space-around",
       padding: 10,
       width: "100%",
       borderBlockColor: colors.bg_2,
       borderBottomWidth: 5,
     },
     _2d_Set: {
       alignItems: "center",
       justifyContent: "center",
     },
     _2d_Value: {
       alignItems: "center",
       justifyContent: "center",
     },
     _2d_Result: {
       alignItems: "center",
       justifyContent: "center",
     },
     _2d_h: {
       fontSize: 14,
       color: colors.text_2,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
       padding: 5,
     },
     _2d_d: {
       fontSize: 18,
       color: colors.app_4,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
     },
     _2d_interCon: {
       flex: 1,
       flexDirection: "row",
       alignItems: "center",
       justifyContent: "space-between",
       width: "100%",
       borderBottomColor: colors.bg_2,
       borderBottomWidth: 4,
       paddingHorizontal: 10,
     },
     _2d_interCon2: {
       paddingHorizontal: 10,
       flex: 1,
       flexDirection: "row",
       alignItems: "center",
       justifyContent: "space-between",
       width: "100%",
       borderBottomColor: colors.app_1,
       borderBottomWidth: 4,
     },
     _2d_interH: {
       color: colors.text_1,
       fontSize: 19,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
     },
     _2d_interBox: {
       alignItems: "center",
       padding: 5,
     },
     _2d_interh: {
       fontSize: 12,
       fontFamily: "Roboto_Bold",
       fontWeight: "700",
       color: colors.text_2,
     },
     _2d_interD: {
       fontSize: 16,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
       color: colors.app_2,
     },
     //bet Btn
     bet2DBtn: {
       position: "absolute",
       bottom: 30,
       left: "20%",
       right: "20%",
       backgroundColor: colors.bg_2,
       justifyContent: "center",
       alignItems: "center",
       padding: 20,
       borderRadius: "50%",
       borderTopColor: colors.app_1,
       borderTopWidth: 1,
       borderColor: colors.app_1,
       borderWidth: 2,
     },
     bet2DBtnTxt: {
       fontSize: 19,
       color: colors.app_4,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
     },
     ////bet ROUTE
     _betContainer: {
       flex: 1,
       justifyContent: "center",
       alignItems: "center",
       backgroundColor: colors.bg_2,
     },
     _betFormBox: {
       width: "90%",
       backgroundColor: colors.bg_3,
       height: "75%",
       borderRadius: 10,
       justifyContent: "space-between",
       alignItems: "center",
       paddingTop: 10,
     },
     _betForm: {
       flexDirection: "row",
       padding: 10,
       width: "90%",
       backgroundColor: colors.bg_2,
       justifyContent: "space-around",
       alignItems: "center",
       borderRadius: 10,
     },
     pairInput: {
       backgroundColor: colors.bg_3,
       color: colors.app_1,
       flex: 1.5,
       padding: 10,
       borderRadius: 5,
       marginHorizontal: 10,
     },
     _betPairTxt: {
       fontSize: 19,
       color: colors.app_4,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
     },
     changeAmountBtn: {
       backgroundColor: colors.app_2,
       padding: 10,
       borderRadius: 10,
       flex: 0.5,
     },
     _confirmOrderBtn: {
       width: "100%",
       paddingVertical: 20,
       justifyContent: "center",
       alignItems: "center",
       backgroundColor: colors.app_1,
       borderBottomLeftRadius: 10,
       borderBottomRightRadius: 10,
     },
     _2d_WinnerBtnCon: {
       position: "absolute",
       left: 10,
       top: 10,
     },
     _2d_WinnerBtn: {
       width: 80,
       height: 80,
     },
     //his btn
     _2d_historyBtnCon: {
       position: "absolute",
       left: 25,
       bottom: 20,
       padding: 10,
       borderRadius: 10,
       backgroundColor: colors.app_1,
     },
     btnTxt1: {
       fontSize: 14,
       color: colors.text_1b,
       fontFamily: "Roboto_Bold",
       fontWeight: "900",
     },
     ///calender lotttie
     calenderCon: {
       position: "absolute",
       width: 55,
       height: 55,
       right: 25,
       top: 30,
     },
     calender: {
       flex: 1,
       shadowColor: colors.bg_1,
       shadowOffset: { x: 10, y: 20 },
       shadowOpacity: 0.5,
       shadowRadius: 10,
     },
     //Timmer
     _2d_Timer: {
       justifyContent: "center",
       paddingTop: 20,
     },
     //bet button
     betBtnCon: {
       width: 150,
       height: 150,
       //backgroundColor: colors.bg_2,
       position: "absolute",
       top: "20%",
       right: "-5%",
     },
     betnow: {
       flex: 0.7,
     },
     close: {
       flex: 1,
     },

     ////3D Bet Screen
     betContainer: {
       flex: 1,
       backgroundColor: colors.bg_2,
       justifyContent: "center",
     },
     wheelContainer: {
       justifyContent: "center",
       flexDirection: "row",
       alignItems: "center",
       flex: 1,
     },
     wheelpicker: {
       borderColor: colors.app_1,
       borderWidth: 5,
     },
     wheelpickerM: {
       borderColor: colors.app_2,
       borderWidth: 5,
     },

     //
     betBtnContainer: {
       flex: 1,
       backgroundColor: colors.bg_2,
     },
     betBtnBox: {
       height: 100,
       backgroundColor: colors.bg_2,
       flexDirection: "row",
       justifyContent: "space-around",
       alignItems: "center",
     },
     cleanBtnCon: {
       flexDirection: "row",
       justifyContent: "space-around",
       alignItems: "center",
     },
     cleanBtn: {
       backgroundColor: colors.bg_3b,
       padding: 20,
       width: "25%",
       alignSelf: "center",
       alignItems: "center",
       justifyContent: "center",
       borderRadius: "50%",
       shadowColor: colors.bg_1,
       shadowOffset: { x: 10, y: 20 },
       shadowOpacity: 0.5,
       shadowRadius: 5,
     },
     cleanTxt: {
       fontFamily: "Roboto_Bold",
       fontSize: 18,
       fontWeight: "600",
       color: colors.text_1b,
     },
     BuyTicket: {
       backgroundColor: colors.app_4,
       padding: 20,
       width: "60%",
       alignSelf: "center",
       alignItems: "center",
       justifyContent: "center",
       borderRadius: "50%",
       shadowColor: colors.bg_1,
       shadowOffset: { x: 10, y: 20 },
       shadowOpacity: 0.5,
       shadowRadius: 5,
     },
     buyTxt: {
       fontFamily: "Roboto_Bold",
       fontSize: 18,
       fontWeight: "600",
       color: colors.text_1b,
     },
     selectBtn: {
       padding: 12,
       paddingHorizontal: 30,
       backgroundColor: colors.app_4,
       borderRadius: "25%",
       justifyContent: "center",
       alignItems: "center",
       shadowColor: colors.bg_1,
       shadowOffset: { x: 10, y: 20 },
       shadowOpacity: 0.5,
       shadowRadius: 5,
     },
     selectTxt: {
       fontFamily: "Roboto_Bold",
       fontSize: 18,
       fontWeight: "600",
       color: colors.text_1b,
     },
     betInputBox: {
       flex: 1,
       alignItems: "center",
       justifyContent: "center",
       marginBottom: 10,
     },
     digitInputContainer: {
       flexDirection: "row",
       width: "80%",
       justifyContent: "space-between",
     },
     digitInput: {
       width: "65%",
       padding: 20,
       backgroundColor: colors.bg_3,
       borderLeftColor: colors.app_1,
       borderLeftWidth: 30,
       borderRadius: 10,
       marginVertical: 10,
       fontSize: 17,
       fontFamily: "Roboto_Bold",
       fontWeight: "700",
       color: colors.app_1,
     },
     addBtn: {
       marginVertical: 10,
       width: "30%",
       backgroundColor: colors.app_4,
       borderRadius: 10,
       padding: 10,
       alignItems: "center",
       justifyContent: "center",
     },
     addTxt: {
       fontFamily: "Roboto_Bold",
       fontSize: 18,
       fontWeight: "600",
       color: colors.text_1b,
     },
     amountInput: {
       width: "80%",
       padding: 20,
       backgroundColor: colors.bg_3,
       borderLeftColor: colors.app_1,
       borderLeftWidth: 30,
       borderRadius: 10,
       marginVertical: 10,
       fontSize: 17,
       fontFamily: "Roboto_Bold",
       fontWeight: "700",
       color: colors.app_1,
     },
     digitPairsCon: {
       flex: 0.5,
       backgroundColor: colors.bg_2,
       flexDirection: "row",
       alignItems: "center",
       flexWrap: "nowrap",
       justifyContent: "center",
       borderBottomColor: colors.app_2,
       borderBottomWidth: 1,
       borderTopWidth: 1,
       borderTopColor: colors.app_2,
       shadowColor: colors.app_1,
       shadowOffset: { x: 10, y: 20 },
       shadowOpacity: 0.2,
       shadowRadius: 10,
     },
     Pairs: {
       padding: 18,
       backgroundColor: colors.app_1,
       borderRadius: "100%",
       marginHorizontal: 10,
       shadowColor: colors.bg_1,
       shadowOffset: { x: 10, y: 20 },
       shadowOpacity: 0.5,
       shadowRadius: 5,
     },
     pairsTxt: {
       fontFamily: "Roboto_Bold",
       fontSize: 15,
       fontWeight: "600",
       color: colors.text_1b,
     },
     pairPreCon: {
       height: 50,
       alignSelf: "center",
       justifyContent: "center",
     },
     pairPreTxt: {
       fontFamily: "Roboto_Bold",
       fontSize: 18,
       fontWeight: "600",
       color: colors.app_2,
     },

     ///ballanceContainer
     ballanceContainer: {
       flex: 0.5,
       backgroundColor: colors.bg_2,
       flexDirection: "row",
       justifyContent: "space-between",
       alignItems: "center",
     },
     walletBtn: {
       width: "45%",
       height: 75,
       backgroundColor: colors.bg_3,
       flexDirection: "row",
       alignItems: "center",
       justifyContent: "space-between",
       borderTopEndRadius: "25%",
       borderBottomColor: colors.app_2,
       borderBottomWidth: 2,
       shadowColor: colors.bg_1,
       shadowOffset: { x: 10, y: 20 },
       shadowOpacity: 0.5,
       shadowRadius: 5,
     },
     ballance: {
       width: "100%",
     },
     ballanceH: {
       fontFamily: "Roboto_Bold",
       fontSize: 14,
       color: colors.app_1,
       fontWeight: "600",
     },
     ballanceV: {
       fontFamily: "Roboto_Bold",
       fontSize: 17,
       color: colors.app_4,
       fontWeight: "600",
       margin: 3,
     },
     walletImg: {
       width: 70,
       height: "100%",
     },
     timeCon: {
       width: "30%",
       height: 75,
       backgroundColor: colors.bg_3,
       alignItems: "flex-start",
       borderBottomLeftRadius: "25%",
     },
     clockImg: {
       width: 60,
       height: 60,
     },

     //HISTORY 2D
     History2D: {
       flex: 1,
       backgroundColor: colors.bg_2,
       alignItems: "center",
     },
     pickerCon: {
       width: "80%",
       height: 100,
       alignItems: "center",
       justifyContent: "space-around",
       flexDirection: "row",
     },
     HistContainer: {
       flex: 1,
       width: 350,
     },
     hisItem: {
       width: "100%",
       padding: 10,
       backgroundColor: colors.bg_3,
       marginVertical: 5,
       borderRadius: 5,
       flexDirection: "row",
       justifyContent: "space-around",
     },
     hisTxt: {
       fontSize: 18,
       color: colors.text_1,
     },

     ///TWO_D ANALYSIS
     TwoD_AnalysisCon: {
       flex: 1,
       backgroundColor: colors.bg_2,
       alignItems: "center",
     },
     buttonContainer: {
       flexDirection: "row",
       justifyContent: "space-between",
       alignItems: "center",
       backgroundColor: colors.app_1,
       height: 100,
     },
     btnNumber: {
       backgroundColor: colors.bg_2,
       padding: 10,
       justifyContent: "center",
       alignItems: "center",
       flex: 1,
       borderTopLeftRadius: "50%",
       margin: 5,
       borderBottomRightRadius: 5,
     },
     btnChart: {
       padding: 10,
       backgroundColor: colors.bg_2,
       flex: 1,
       borderTopRightRadius: "50%",
       justifyContent: "center",
       alignItems: "center",
       margin: 5,
       borderBottomLeftRadius: 5,
     },
     numberTxt: {
       fontSize: 16,
       color: colors.app_1,
       fontFamily: "Roboto_Bold",
       fontWeight: "700",
     },
     ///Numbers
     ////
     analHeader: {
       width: "95%",
       backgroundColor: colors.app_4,
       flexDirection: "row",
       justifyContent: "space-around",
       alignItems: "center",
       borderBottomColor: colors.app_1,
       borderTopRightRadius: 10,
       borderTopLeftRadius: 10,
       borderBottomWidth: 6,
     },
     analCon: {
       padding: 5,
     },
     analSelectedTxt: {
       fontSize: 16,
       color: colors.app_2,
       fontFamily: "Roboto_Bold",
       fontWeight: "500",
     },
     analHtxt: {
       fontSize: 15,
       color: colors.bg_1,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
     },
     _filter: {
       flex: 1,
       shadowColor: colors.app_4,
       shadowOffset: { x: 10, y: 20 },
       shadowOpacity: 1,
       shadowRadius: 10,
       backgroundColor: "transparent",
     },
     _filterItem: {
       fontSize: 16,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
       color: colors.bg_1,
     },
     /////
     DyCon: {
       width: "95%",
       height: 50,
       margin: 10,
     },
     ////DynamicNumbers/
     DynamicNumbers: {
       flex: 1,
       flexDirection: "row",
       justifyContent: "space-around",
       padding: 5,
     },
     DyNumbers: {
       padding: 10,
       borderRadius: "100%",
       backgroundColor: colors.app_2,
       justifyContent: "center",
     },
     Numbers: {
       fontSize: 16,
       color: colors.bg_1,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
     },

     //DATA
     analDataContainer: {
       width: "95%",
     },

     analItemCon: {
       flexDirection: "row",
       alignItems: "center",
       justifyContent: "space-around",
       backgroundColor: colors.bg_3,
       marginVertical: 10,
       borderRadius: 10,
       // paddingVertical: 10,
     },
     analItemBox: {
       paddingHorizontal: 10,
       borderLeftWidth: 2,
       borderLeftColor: colors.bg_2,
       paddingVertical: 10,
     },
     analAf: {
       fontSize: 16,
       color: colors.text_1,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
     },
     analItemBox1: {},
     analItemTxt: {
       fontSize: 15,
       color: colors.text_1,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
     },
     analItemTxtd: {
       fontSize: 15,
       color: colors.app_1,
       fontFamily: "Roboto_Bold",
       fontWeight: "600",
     },

     ///
     txt: {
       fontSize: 11,
       color: colors.text_1b,
       fontFamily: "Roboto",
       textAlign: "center",
     },
   });
   return stylesS
}

export default stylesCon;
